### ISSUE TITLE
Issue with downloading filings

### ISSUE THREAD

**Issue by bosanipietro** [jadchaar/sec-edgar-downloader#72]
Thank you for the package!

I have been trying to download S-1 filings but consistently get the same error for most filings: 
`Skipping filing detail download for '0001628280-20-017136' due to network error: 403 Client Error: Forbidden for url: https://www.sec.gov/Archives/edgar/data/0001577526/000162828020017136/c3ais-1a3.htm.`
The line of code that resulted in this output is `dl.get("S-1", "0001577526", amount=1, download_details=True, include_amends=True)`. I am trying to have the filings details (html) rather than the txt output for all filings. 

Also, I seem to have an issue with finding the filings for certain companies. For example, `dl.get("S-1", "0001096219", amount=1, download_details=True, include_amends=True, before='2000-01-24')` results in zero output. However, looking at the SEC website for the corresponding company, there indeed is the file I am searching for (as shown in the attached image). What could be the cause of this problem?
<img width="1389" alt="Screenshot 2021-04-22 at 10 05 19" src="https://user-images.githubusercontent.com/51325989/115679081-79bce380-a352-11eb-9360-27443af5e3dc.png">

I am currently trying to download all details of the last S-1 (or F-1) filing before IPO for a list of companies identified by their CIK since 2000.

**Comment by jadchaar** [comment]
Hi @bosanipietro, which version of this package are you using? You can check by doing
```
>>> import sec_edgar_downloader
>>> sec_edgar_downloader.__version__
```

**Comment by bosanipietro** [comment]
Version 4.0.1

**Comment by jadchaar** [comment]
Try updating to version 4.0.3 with `pip install -U sec-edgar-downloader` as that should resolve the issue (ref: https://github.com/jadchaar/sec-edgar-downloader/issues/68).

**Comment by jadchaar** [comment]
Feel free to re-open if necessary, but 4.0.3 should be the resolution :)!

**Comment by bosanipietro** [comment]
Sorry to bother you again but I’m still having some troubles.
I tried updating the library using the command you suggested and imported it again. I then tried to check for the version, but keep seeing 4.0.1. Do you know why this could be the case?

Thank you very much for your help.
Pietro Bosani

From: Jad Chaar ***@***.***>
Date: Thursday, 22 April 2021 at 18:57
To: jadchaar/sec-edgar-downloader ***@***.***>
Cc: bosanipietro ***@***.***>, Mention ***@***.***>
Subject: Re: [jadchaar/sec-edgar-downloader] Issue with downloading filings (#72)

Feel free to re-open if necessary, but 4.0.3 should be the resolution :)!

**Comment by bosanipietro** [comment]
Unfortunately even after updating the package version, dl.get still cannot find and download existing files (as example shown above). Would you have any other suggestions on what may be causing this issue?

**Comment by jadchaar** [comment]
Hi @bosanipietro, thanks for following up. I get the following output from your commands on v4.0.3:

```python
env ❯ python3
Python 3.9.4 (default, Apr  5 2021, 01:50:46)
[Clang 12.0.0 (clang-1200.0.32.29)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from sec_edgar_downloader import Downloader
>>> dl = Downloader()
>>> dl.get("S-1", "0001096219", amount=1, download_details=True, include_amends=True, before='2000-01-24')
0
>>> dl.get("S-1", "0001577526", amount=1, download_details=True, include_amends=True)
1
```

It seems like the first command is failing to fetch any filings because the SEC Edgar search system at the core of this package does not fetch filings before 2001: https://www.sec.gov/edgar/search/#/q=0001096219&dateRange=all&category=custom&forms=S-1. I recently moved over to this new SEC Search API for this package since it was much more streamlined and powerful than the old scraping system I was using, but as a side effect filings before 2001 are not included.

**Comment by bosanipietro** [comment]
You are right, it only has issues with filings before 2001. Thank you very much for your help!
Would you be able to answer just one last question, as in some cases I am still getting the error message because it cannot download the filing details for certain CIK codes: what is the difference between the full submission txt and the filing details txt?

**Comment by jadchaar** [comment]
Happy to answer questions! The full submission is a massive text file containing all the info you need for a filing, but it may require more complex parsing methods. The filing details are supplementary docs that might be helpful for particular filings (they might be XMLs with numbers that are more easily parseable). Also the filing details might be more human readable HTML forms that can be opened in a browser depending on the filing.

**Comment by bosanipietro** [comment]
Does the filing detail actually contain all of the information of the filing? Because I was comparing one of the outcomes to the S-1 filing as shown on the SEC website and the filing detail when in html form seems to resemble the latter very closely. The full submission, as you stated, is extremely large and for a natural language processing task I am having serious difficulty in cleaning the data to get only the textual information of the filing. Do you think the filing detail could be sufficient for a IPO underpricing prediction task?

From: Jad Chaar ***@***.***>
Date: Friday, 23 April 2021 at 17:13
To: jadchaar/sec-edgar-downloader ***@***.***>
Cc: bosanipietro ***@***.***>, Mention ***@***.***>
Subject: Re: [jadchaar/sec-edgar-downloader] Issue with downloading filings (#72)

Happy to answer questions! The full submission is a massive text file containing all the info you need for a filing, but it may require more complex parsing methods. The filing details are supplementary docs that might be helpful for particular filings (they might be XMLs with numbers that are more easily parseable). Also the filing details might be more human readable HTML forms that can be opened in a browser depending on the filing.

**Comment by jadchaar** [comment]
I have not dealt with S-1s enough to comment on that, but I'd take a look at the filing details doc to see if it contains the equivalent data you are looking for from the full submission :)!
